version: '3.4'

services:
  catalogdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432" 
    
     
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
 
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:
  postgres_catalog:


